dist: focal

before_install:
  - sudo bash -c 'set -o noglob; while true; do found=0; for x in $(which -a phantomjs); do test -e "$x" || continue; found=1; rm -f "$x"; done; test $found = 1 || break; done'
  - npm install -g phantomjs@1.9.20

language: node_js
node_js:
  - 18

addons:
  apt:
    packages:
    - ed
    - jsdoc-toolkit
    - libjs-bootstrap
    - libjs-jquery
    - pax
    - python-is-python2

script: >
    npm run build &&
    npm run build-tests &&
    npm run test &&
    npm run coverage &&
    ./scripts/post-coverage.sh &&
    ./scripts/weigh-in.sh
