dist: focal

language: node_js
node_js:
  - 18

script: >
    npm run build &&
    npm run build-tests &&
    npm run test &&
    npm run coverage &&
    ./scripts/post-coverage.sh &&
    ./scripts/weigh-in.sh
