dist: focal

before_install:
  - env TMPDIR=/tmp npm install -g phantomjs@1.9.20

addons:
  apt:
    packages:
    - ed
    - jsdoc-toolkit
    - libjs-bootstrap
    - libjs-jquery
    - pax
    - python-is-python2

script: >
    npm run build &&
    npm run build-tests &&
    npm run test &&
    npm run coverage &&
    ./scripts/post-coverage.sh &&
    ./scripts/weigh-in.sh
